name: Preview Deployment

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  sync_submodules:
    name: 'Submodules Sync'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout submodules
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.APP_CI_TOKEN }}
        submodules: true
        fetch-depth: 0

  # lint:
  #   name: 'Superlinter'
  #   runs-on: ubuntu-latest

  #   permissions:
  #     contents: read
  #     packages: read
  #     # To report GitHub Actions status checks
  #     statuses: write
    
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #       with:
  #         # Full git history is needed to get a proper list of changed files within `super-linter`
  #         fetch-depth: 0

  #     - name: Lint Code Base
  #       uses: github/super-linter/slim@v4
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         DEFAULT_BRANCH: "main"
  #         VALIDATE_ALL_CODEBASE: true
  #         LINTER_RULES_PATH: "/"
  #         CSS_FILE_NAME: ".stylelintrc.yml"
  #         TYPESCRIPT_ES_CONFIG_FILE: ".eslintrc.yml"
  #         VALIDATE_TSX: true
  #         VALIDATE_TYPESCRIPT_ES: true
  #         VALIDATE_CSS: true


  security:
    name: Snyk Security
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Snyk
      uses: snyk/actions@0.4.0
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_AUTH_TOKEN }}
      with:
        command: monitor

